#!/bin/python
# -*- coding: utf-8 -*-
import os,re
fo =os.popen('gluster volume info')
info = fo.readlines()
volinfo ={}
vol=[]
n=0
for line in info :
    if line.strip():
       item=line.strip('\n').split(":",1)[0]
       value=line.strip('\n').split(":",1)[1]
       if  re.match('Brick[0-9]+',item):
           volinfo['Bricks']= volinfo['Bricks']+value+"##"
       else:
           volinfo[item] = value
    else:
       volinfo={}
       vol.append(volinfo)
#print vol
for count in range(1,len(vol)):
    print count
    print vol[count]['Bricks']

