#!/usr/bin/python
#-*- coding:utf8 -*-
import os,re
path = "/etc/sysconfig/network-scripts/"

def interface(device,bootproto,ipaddr,netmask,gateway):
    if (device == "" or bootproto == "" or
        ipaddr  == "" or netmask == "" or gateway == ""):
        return "not correct parameters "
    else:
         ipconfiglines=[]
         config_file=path+"ifcfg-"+device
         ipconfiglines.append('DEVICE=' + device+'\n')
         ipconfiglines.append('ONBOOT=yes'+'\n')
         ipconfiglines.append('BOOTPROTO='+bootproto+'\n')
         ipconfiglines.append('IPADDR=' + ipaddr+'\n')
         ipconfiglines.append('NETMASK=' +netmask+'\n')
         ipconfiglines.append('GATEWAY='+gateway+'\n')
         # print ipconfiglines
         pattern = re.compile('DEVICE|ONBOOT|BOOTPROTO|IPADDR|NETMASK|GATEWAY')
         try:
             with open(config_file,'r') as f:
                lines = f.readlines()
             with open(config_file,'w') as f_w:
                 f_w.writelines(ipconfiglines)
                 for line in lines:
                    if not re.search(pattern,line):
                       # print line
                       f_w.write(line)
             return "Secessful"
         except  :
             return "file is not exist"
    # return  "ok"
print interface("eno16777736","none","192.168.1.30","255.255.255.0","192.168.1.1")
